apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps1
spec:
  project: aoa-sync-waves
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/dhpup/aoa-sync-waves.git
    targetRevision: main
    path: apps1
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd